// Generated by Wrangler on Tue Jul 22 2025 13:13:17 GMT+0200 (heure d’été d’Europe centrale)
// by running `wrangler types`

interface Env {
		D1_lists: D1Database;		PUSHER_APP_ID: string;
		PUSHER_KEY: string;
		PUSHER_SECRET: string;
		PUSHER_CLUSTER: string;}
