// Generated by Wrangler on Tue Jul 22 2025 13:13:17 GMT+0200 (heure d’été d’Europe centrale)
// by running `wrangler types`

interface Env {
		D1_lists: D1Database;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		GOOGLE_REDIRECT_URI: string;
}
