// Generated by Wrangler on Tue Jul 22 2025 13:13:17 GMT+0200 (heure d’été d’Europe centrale)
// by running `wrangler types`

export interface Env {
    D1_lists: D1Database
    CLIENT_ID: string
    CLIENT_SECRET: string
    REDIRECT_URI: string
    AUTH_ENDPOINT: string
    TOKEN_ENDPOINT: string
    TOKEN_VERIFICATION_ENDPOINT: string
    SCOPE: string
    ASSETS: Fetcher
}
